# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lampu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30, unique=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
