# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam', models.TimeField()),
                ('state', models.BooleanField(default=False)),
                ('lampu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lamp.Lampu')),
            ],
        ),
    ]
